(()=>{
const STORY={title:'The Night the City Lost Its Music',scenes:[
 {name:'Wake the Streetlights',icon:'💡',lesson:'cause + beat',prompt:'The city is dark. Find the sound that wakes the lights!',pattern:[0,0,0,0],success:'One sound. Four lights. The street is awake!'},
 {name:'Open the Bridge',icon:'🌉',lesson:'sequence',prompt:'The bridge needs a musical code. Build it in order.',pattern:[0,1,0,1],success:'C-D, C-D! The bridge remembers how to move!'},
 {name:'Echo Tunnel',icon:'🔊',lesson:'memory',prompt:'Listen to the tunnel. Then play its echo back.',pattern:[0,1,2,1],success:'You remembered the echo! The tunnel is singing again.'},
 {name:'Bring Music Home',icon:'✨',lesson:'pattern transfer',prompt:'The whole city needs one last melody. Bring every sound home!',pattern:[0,1,2,3],success:'C-D-E-F! The music is back!'}
]};
let active=false,scene=0,step=0,locked=false,box=null,originalHit=null;
const $=id=>document.getElementById(id),labels=['C','D','E','F'];
function ensureBox(){if(box)return;box=document.createElement('div');box.className='storyMission';box.style.display='none';document.getElementById('stage').appendChild(box)}
function speak(text){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.92;u.pitch=1.12;u.volume=.9;speechSynthesis.speak(u)}catch{}}
function tone(lane,delay=0){setTimeout(()=>{try{noteSound(lane,'perfect')}catch{}},delay)}
function glow(lane,on=true){const k=document.querySelector('.pianoKey[data-lane="'+lane+'"]');if(k)k.classList.toggle('storyHint',on)}
function clearGlow(){document.querySelectorAll('.pianoKey').forEach(k=>k.classList.remove('storyHint'))}
function render(){ensureBox();const s=STORY.scenes[scene];box.style.display='block';box.innerHTML='<div class="storyMissionTop"><span>'+s.icon+' CHAPTER '+(scene+1)+'/4</span><b>'+s.name.toUpperCase()+'</b></div><div class="storyMissionText">'+s.prompt+'</div><div class="storyDots">'+s.pattern.map((n,i)=>'<span class="'+(i<step?'done':i===step?'now':'')+'">'+labels[n]+'</span>').join('')+'</div>';clearGlow();if(scene!==2&&!locked)glow(s.pattern[step],true)}
function playEcho(){locked=true;clearGlow();box.querySelector('.storyMissionText').textContent='Listen… remember the sound.';const p=STORY.scenes[scene].pattern;p.forEach((n,i)=>tone(n,i*520));setTimeout(()=>{locked=false;step=0;box.querySelector('.storyMissionText').textContent='Your turn. Play the echo back!';render();clearGlow()},p.length*520+450)}
function beginScene(){step=0;locked=false;render();const s=STORY.scenes[scene];speak(s.prompt);if(scene===2)setTimeout(playEcho,900)}
function celebrate(){const s=STORY.scenes[scene];locked=true;clearGlow();showFlash(scene===3?'MUSIC IS BACK!':'CHAPTER CLEAR!','#ffd166',true);speak(s.success);box.querySelector('.storyMissionText').textContent=s.success;box.querySelectorAll('.storyDots span').forEach(x=>x.className='done');setTimeout(()=>{if(scene<3){scene++;beginScene()}else finishStory()},2200)}
function finishStory(){active=false;locked=false;clearGlow();if(box)box.style.display='none';const first=localStorage.getItem('carkeys-story-1')!=='1';localStorage.setItem('carkeys-story-1','1');if(first){try{coins+=150;saveMeta()}catch{}}showFlash('CITY SAVED!','#7df0a3',true);speak('You brought the music home. The whole city can sing again!');setTimeout(()=>{try{running=false;cancelAnimationFrame(raf);stopAudio()}catch{};$('finalScore').textContent='STORY';$('finalAccuracy').textContent='4/4';$('finalCombo').textContent='MUSIC';$('finalPlace').textContent='HERO';$('stars').textContent='★★★★';$('unlock').innerHTML=(first?'🎁 <strong>Story Star + 150 coins!</strong>':'✨ <strong>Story complete!</strong>')+' The city has its music back.';$('unlock').classList.add('show');$('endOverlay').querySelector('h2').textContent='THE CITY SINGS AGAIN 🌃🎶';$('endOverlay').style.display='grid'},1200)}
function storyHit(lane){if(!active||locked)return false;const s=STORY.scenes[scene],want=s.pattern[step];try{noteSound(lane,lane===want?'perfect':'miss')}catch{}if(lane===want){glow(want,false);step++;try{targetLane=lane;speed=Math.min(130,speed+8);score+=600;boost=Math.min(100,boost+8);updateHud();buzz(18)}catch{}if(step>=s.pattern.length)celebrate();else render()}else{showFlash('LISTEN AGAIN','#67e8ff',false);try{buzz(25)}catch{}step=0;render();if(scene===2)setTimeout(playEcho,450)}return true}
function startStory(){active=true;scene=0;step=0;locked=false;$('storyOverlay').style.display='none';$('homeOverlay').style.display='none';$('pauseBtn').style.visibility='visible';try{tutorialMode=false;bossMode=false;freePlay=true;prepare();running=true;startTime=performance.now();lastT=startTime;startAudio();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);modeBadge.textContent='STORY MODE · CITY OF MUSIC';modeBadge.classList.add('raceTypePill')}catch{}beginScene()}
function hook(){ensureBox();$('storyMenuBtn').onclick=()=>{$('homeOverlay').style.display='none';$('storyOverlay').style.display='grid'};$('storyBackBtn').onclick=()=>{$('storyOverlay').style.display='none';$('homeOverlay').style.display='grid'};$('storyStartBtn').onclick=startStory;document.querySelectorAll('.pianoKey').forEach(b=>b.addEventListener('pointerdown',e=>{if(active){e.stopImmediatePropagation();e.preventDefault();storyHit(+b.dataset.lane)}},true));window.addEventListener('keydown',e=>{if(!active||e.repeat)return;const m={a:0,s:1,d:2,f:3};if(m[e.key.toLowerCase()]!==undefined){e.stopImmediatePropagation();e.preventDefault();storyHit(m[e.key.toLowerCase()])}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})();